#lane_control/lane_controller_node
#v_bar_old 0.45
v_bar: 0.2064 #defalut=0.3864
# k_d_old: -12
k_d: -15.30 #default=-10.30
# k_theta_old: -6.0
k_theta: -0.15 #default=-5.15
theta_thres: 0.523
d_thres: 0.2615
d_offset: 0.0

